import { Link } from 'react-router';
import { ArrowLeft } from 'lucide-react';
import logo from '@/assets/menukit-logo.svg';

export function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-2xl shadow-sm border border-slate-200">
        <div className="mb-8 flex items-center justify-between">
          <Link to="/" className="text-slate-500 hover:text-primary transition-colors flex items-center font-semibold">
            <ArrowLeft size={20} className="mr-2" /> Back
          </Link>
          <img src={logo} alt="MenuKit Logo" className="w-8 h-8" />
        </div>
        
        <h1 className="text-3xl md:text-4xl font-bold font-heading mb-8 text-slate-900">Terms and Conditions</h1>
        
        <div className="prose prose-slate max-w-none text-sm md:text-base text-slate-600 space-y-8">
          <p className="text-lg text-slate-700 font-medium leading-relaxed">
            Welcome to MenuKit. By accessing, browsing, or using our platform, digital menu services, and related applications (collectively referred to as the "Service"), you acknowledge that you have read, understood, and agree to be legally bound by these Terms and Conditions. These terms apply to all visitors, users, restaurant partners, and others who access or use the Service. If you disagree with any part of the terms, you must immediately discontinue your use of the Service.
          </p>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-4">1. Acceptance of Terms & IT Act Compliance</h2>
            <p className="leading-relaxed">
              This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. Your continued use of the MenuKit platform signifies your acceptance of these electronically binding terms and conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-4">2. Account Registration and Responsibilities</h2>
            <p className="leading-relaxed">
              To fully utilize the features offered by MenuKit, you are required to create a user account. You agree to provide accurate, current, and complete information during the registration process and to keep this information up-to-date. You are solely responsible for safeguarding the confidentiality of your account credentials, including your password, and for all activities that occur under your account. MenuKit reserves the right to suspend or terminate accounts that are suspected of fraudulent activity, providing inaccurate data, or violating any provisions of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-4">3. Prohibited Conduct and Acceptable Use</h2>
            <p className="leading-relaxed">
              You agree to use MenuKit only for lawful purposes. You are strictly prohibited from utilizing the Service to transmit, distribute, store, or destroy material in violation of any applicable law or regulation. Furthermore, you must not engage in any activity that interferes with or disrupts the Service, its servers, or networks connected to the Service. This includes attempting to gain unauthorized access to any portion of the platform, conducting vulnerability scanning, or deploying malicious software such as viruses or trojan horses. Any such breach will result in immediate termination of your access and may lead to legal action.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-4">4. Intellectual Property Rights</h2>
            <p className="leading-relaxed">
              The MenuKit Service and its original content, features, and functionality are and will remain the exclusive property of MenuKit and its licensors. The Service is protected by copyright, trademark, and other laws of both India and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of MenuKit. By uploading your restaurant's logo, menus, or promotional images ("User Content"), you grant MenuKit a non-exclusive, worldwide, royalty-free license to use, display, and reproduce your User Content solely for the purpose of operating and promoting the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-4">5. Disclaimer of Warranties and Limitation of Liability</h2>
            <p className="leading-relaxed">
              Your use of the MenuKit Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement. In no event shall MenuKit, its directors, employees, or partners be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to loss of profits, data, or goodwill, even if we have been advised of the possibility of such damages.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-800 mb-4">6. Modifications to Terms</h2>
            <p className="leading-relaxed">
              MenuKit reserves the right, at our sole discretion, to modify or replace these Terms at any time. We will provide reasonable notice of any material changes via the platform or email. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.
            </p>
          </section>
          
          <div className="pt-8 border-t border-slate-200">
            <p className="text-sm font-bold text-slate-500">
              Last updated: August 19, 2026
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
