import { Link } from 'react-router';
import { ArrowLeft } from 'lucide-react';
import logo from '@/assets/menukit-logo.svg';

export function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
        <div className="mb-8 flex items-center justify-between">
          <Link to="/" className="text-slate-500 hover:text-primary transition-colors flex items-center">
            <ArrowLeft size={20} className="mr-2" /> Back
          </Link>
          <img src={logo} alt="MenuKit Logo" className="w-8 h-8" />
        </div>
        
        <h1 className="text-3xl font-bold font-heading mb-6">Terms and Conditions</h1>
        
        <div className="prose prose-slate max-w-none text-sm text-slate-600 space-y-6">
          <p>
            Welcome to MenuKit. By accessing or using our service, you agree to be bound by these Terms and Conditions and our Privacy Policy. 
            If you do not agree with any part of these terms, you may not use our service.
          </p>

          <h2 className="text-lg font-bold text-slate-800">1. Information Technology Act Compliance</h2>
          <p>
            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <h2 className="text-lg font-bold text-slate-800">2. Use of Service</h2>
          <p>
            MenuKit provides a digital menu management and QR code generation service for restaurants and cafes. You agree to use the service only for lawful purposes and in a way that does not infringe the rights of, restrict or inhibit anyone else's use and enjoyment of the service.
          </p>

          <h2 className="text-lg font-bold text-slate-800">3. User Accounts</h2>
          <p>
            When you create an account with us, you must provide accurate, complete, and current information at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our service.
          </p>

          <h2 className="text-lg font-bold text-slate-800">4. Content Ownership</h2>
          <p>
            Our service allows you to post, link, store, share and otherwise make available certain information, text, graphics, or other material ("Content"). You are responsible for the Content that you post on or through the service, including its legality, reliability, and appropriateness.
          </p>

          <h2 className="text-lg font-bold text-slate-800">5. Limitation of Liability</h2>
          <p>
            In no event shall MenuKit, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.
          </p>

          <h2 className="text-lg font-bold text-slate-800">6. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our service after those revisions become effective, you agree to be bound by the revised terms.
          </p>
          
          <p className="pt-4 text-xs text-slate-400">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
}
